# Generated by Django 3.0.2 on 2020-05-31 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentPage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coursetmp',
        ),
    ]
