# Generated by Django 3.0.2 on 2020-06-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentPage', '0002_delete_coursetmp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doubts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=300)),
                ('receiver', models.CharField(max_length=40)),
                ('course', models.CharField(max_length=40)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
