# Generated by Django 3.0.2 on 2020-07-09 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorPage', '0010_auto_20200709_1637'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studentPage', '0003_doubts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubts',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorPage.Course'),
        ),
        migrations.AlterField(
            model_name='doubts',
            name='message',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='doubts',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doubts',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
