# Generated by Django 3.0.2 on 2020-07-09 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='course',
            name='members',
        ),
        migrations.RemoveField(
            model_name='doubts',
            name='course',
        ),
        migrations.RemoveField(
            model_name='doubts',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='doubts',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Chats',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Doubts',
        ),
    ]
