# Generated by Django 3.0.2 on 2020-05-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='Courses', to='mentorPage.Users_id'),
        ),
    ]
