# Generated by Django 3.0.2 on 2020-05-29 12:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentorPage', '0002_auto_20200529_0941'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users_id',
        ),
        migrations.AlterField(
            model_name='course',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='Courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
