# Generated by Django 3.0.2 on 2020-06-11 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mentorPage', '0004_chats'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
