# Generated by Django 3.0.2 on 2020-06-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorPage', '0005_chats_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='message',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
