# Generated by Django 3.0.2 on 2020-06-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorPage', '0006_auto_20200611_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
