# Generated by Django 3.0.2 on 2020-06-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorPage', '0007_auto_20200611_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
